# Form implementation generated from reading ui file 'ui/interface.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import cv2
import qimage2ndarray
import numpy as np


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 731)
        MainWindow.setStyleSheet("background-color: rgb(70, 70, 70);")

        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(70, 70, 70);")
        self.centralwidget.setObjectName("centralwidget")

        self.gridLayout_10 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_10.setObjectName("gridLayout_10")

        # Главный лей-аут
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")

        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setStyleSheet("background-color: rgb(70, 70, 70);")
        self.tabWidget.setObjectName("tabWidget")


        # Таб с камерами
        self.tab_camera_mode = QtWidgets.QWidget()
        self.tab_camera_mode.setObjectName("tab_camera_mode")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_camera_mode)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetNoConstraint)
        self.gridLayout_2.setContentsMargins(-1, -1, 0, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")

        # кнопка сторта ???маленькая???
        self.lil_play_btn = QtWidgets.QPushButton(parent=self.tab_camera_mode)
        self.lil_play_btn.setMinimumSize(QtCore.QSize(10, 65))
        self.lil_play_btn.setMaximumSize(QtCore.QSize(60, 65))
        self.lil_play_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/play2.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.lil_play_btn.setIcon(icon)
        self.lil_play_btn.setIconSize(QtCore.QSize(75, 75))
        self.lil_play_btn.setObjectName("lil_play_btn")
        self.gridLayout_2.addWidget(self.lil_play_btn, 3, 2, 1, 1)

        # Кнопка настройки камер
        self.video_set_btn = QtWidgets.QPushButton(parent=self.tab_camera_mode)
        self.video_set_btn.setMinimumSize(QtCore.QSize(60, 70))
        self.video_set_btn.setMaximumSize(QtCore.QSize(60, 16777215))
        self.video_set_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/set_cam.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.video_set_btn.setIcon(icon1)
        self.video_set_btn.setIconSize(QtCore.QSize(34, 34))
        self.video_set_btn.setObjectName("video_set_btn")
        self.gridLayout_2.addWidget(self.video_set_btn, 11, 2, 1, 1)

        #
        self.videocam_label = QtWidgets.QLabel(parent=self.tab_camera_mode)
        self.videocam_label.setMaximumSize(QtCore.QSize(300, 70))
        self.videocam_label.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.videocam_label.setObjectName("videocam_label")
        self.gridLayout_2.addWidget(self.videocam_label, 0, 0, 1, 2)

        # кнопка дирректории для сохранения
        self.save_dir_btn = QtWidgets.QPushButton(parent=self.tab_camera_mode)
        self.save_dir_btn.setMinimumSize(QtCore.QSize(56, 65))
        self.save_dir_btn.setMaximumSize(QtCore.QSize(60, 65))
        self.save_dir_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/papka.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.save_dir_btn.setIcon(icon2)
        self.save_dir_btn.setIconSize(QtCore.QSize(33, 37))
        self.save_dir_btn.setObjectName("save_dir_btn")
        self.gridLayout_2.addWidget(self.save_dir_btn, 2, 2, 1, 1)

        # Лэй аут с панелями
        self.grid_with_panels = QtWidgets.QGridLayout()
        self.grid_with_panels.setContentsMargins(-1, 6, 10, -1)
        self.grid_with_panels.setObjectName("grid_with_panels")

        self.panel = QtWidgets.QLabel(parent=self.tab_camera_mode)
        self.panel.setStyleSheet("border: 3px solid rgba(255,255,255,200);\n"
                                 "border-radius: 15px;\n"
                                 "background-color: rgb(221, 221, 221);")
        self.panel.setLineWidth(0)
        self.panel.setText("")
        self.panel.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.panel.setScaledContents(True)
        self.panel.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignBottom | QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft)
        self.panel.setObjectName("panel")
        self.grid_with_panels.addWidget(self.panel, 0, 0, 1, 1)

        self.panel2 = QtWidgets.QLabel(parent=self.tab_camera_mode)
        self.panel2.setStyleSheet("border: 3px solid rgba(255,255,255,200);\n"
"border-radius: 15px;\n"
"background-color: rgb(221, 221, 221);")
        self.panel2.setText("")
        self.panel2.setObjectName("panel2")
        self.grid_with_panels.addWidget(self.panel2, 0, 1, 1, 1)

        self.panel3 = QtWidgets.QLabel(parent=self.tab_camera_mode)
        self.panel3.setStyleSheet("border: 3px solid rgba(255,255,255,200);\n"
"border-radius: 15px;\n"
"background-color: rgb(221, 221, 221);")
        self.panel3.setText("")
        self.panel3.setObjectName("panel3")
        self.grid_with_panels.addWidget(self.panel3, 0, 2, 1, 1)

        self.panel4 = QtWidgets.QLabel(parent=self.tab_camera_mode)
        self.panel4.setStyleSheet("border: 3px solid rgba(255,255,255,200);\n"
"border-radius: 15px;\n"
"background-color: rgb(221, 221, 221);")
        self.panel4.setText("")
        self.panel4.setObjectName("panel4")
        self.grid_with_panels.addWidget(self.panel4, 1, 0, 1, 1)

        self.panel5 = QtWidgets.QLabel(parent=self.tab_camera_mode)
        self.panel5.setStyleSheet("border: 3px solid rgba(255,255,255,200);\n"
                                  "border-radius: 15px;\n"
                                  "background-color: rgb(221, 221, 221);")
        self.panel5.setText("")
        self.panel5.setObjectName("panel5")
        self.grid_with_panels.addWidget(self.panel5, 1, 1, 1, 1)

        self.panel6 = QtWidgets.QLabel(parent=self.tab_camera_mode)
        self.panel6.setStyleSheet("border: 3px solid rgba(255,255,255,200);\n"
"border-radius: 15px;\n"
"background-color: rgb(221, 221, 221);")
        self.panel6.setText("")
        self.panel6.setObjectName("panel6")
        self.grid_with_panels.addWidget(self.panel6, 1, 2, 1, 1)

        self.panel7 = QtWidgets.QLabel(parent=self.tab_camera_mode)
        self.panel7.setStyleSheet("border: 3px solid rgba(255,255,255,200);\n"
"border-radius: 15px;\n"
"background-color: rgb(221, 221, 221);")
        self.panel7.setText("")
        self.panel7.setObjectName("panel7")
        self.grid_with_panels.addWidget(self.panel7, 2, 0, 1, 1)

        self.panel8 = QtWidgets.QLabel(parent=self.tab_camera_mode)
        self.panel8.setStyleSheet("border: 3px solid rgba(255,255,255,200);\n"
                                  "border-radius: 15px;\n"
                                  "background-color: rgb(221, 221, 221);")
        self.panel8.setText("")
        self.panel8.setObjectName("panel8")
        self.grid_with_panels.addWidget(self.panel8, 2, 1, 1, 1)

        self.panel9 = QtWidgets.QLabel(parent=self.tab_camera_mode)
        self.panel9.setStyleSheet("border: 3px solid rgba(255,255,255,200);\n"
"border-radius: 15px;\n"
"background-color: rgb(221, 221, 221);")
        self.panel9.setText("")
        self.panel9.setObjectName("panel9")
        self.grid_with_panels.addWidget(self.panel9, 2, 2, 1, 1)

        # кнопки справа
        self.gridLayout_2.addLayout(self.grid_with_panels, 1, 0, 11, 2)
        self.sun_btn = QtWidgets.QPushButton(parent=self.tab_camera_mode)
        self.sun_btn.setMinimumSize(QtCore.QSize(60, 65))
        self.sun_btn.setMaximumSize(QtCore.QSize(57, 65))
        self.sun_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/sun.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.sun_btn.setIcon(icon3)
        self.sun_btn.setIconSize(QtCore.QSize(57, 65))
        self.sun_btn.setObjectName("sun_btn")
        self.gridLayout_2.addWidget(self.sun_btn, 1, 2, 1, 1)

        # Кнопка пуска камер
        self.big_play_btn = QtWidgets.QPushButton(parent=self.tab_camera_mode)
        self.big_play_btn.setMinimumSize(QtCore.QSize(12, 0))
        self.big_play_btn.setMaximumSize(QtCore.QSize(65, 65))
        self.big_play_btn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/play.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.big_play_btn.setIcon(icon4)
        self.big_play_btn.setIconSize(QtCore.QSize(65, 65))
        self.big_play_btn.setObjectName("big_play_btn")
        self.gridLayout_2.addWidget(self.big_play_btn, 0, 2, 1, 1)

        # Добавление табов
        self.gridLayout_2.setRowStretch(0, 1)
        self.tabWidget.addTab(self.tab_camera_mode, "")
        self.tab_neuro_mode = QtWidgets.QWidget()
        self.tab_neuro_mode.setObjectName("tab_neuro_mode")
        self.tabWidget.addTab(self.tab_neuro_mode, "")
        self.tab_3d_mode = QtWidgets.QWidget()
        self.tab_3d_mode.setObjectName("tab_3d_mode")
        self.tabWidget.addTab(self.tab_3d_mode, "")
        self.gridLayout_8.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_8, 0, 1, 1, 1)

        self.display = QtWidgets.QLabel(self.tab_3d_mode)
        self.display.setGeometry(10, 10, 750, 600)
        self.display.setStyleSheet("border: 3px solid rgba(255,255,255,200);\n"
                                    "border-radius: 15px;\n"
                                    "background-color: rgb(221, 221, 221);")
        self.display.setText("")
        self.display.setObjectName("display")

        self.load_file_btn = QtWidgets.QPushButton(self.tab_3d_mode)
        self.load_file_btn.setGeometry(765, 10, 120, 40)
        self.load_file_btn.setText("Загрузить")
        self.load_file_btn.setObjectName("load_file_btn")

        self.center_btn = QtWidgets.QPushButton(self.tab_3d_mode)
        self.center_btn.setGeometry(765, 55, 120, 40)
        self.center_btn.setText("Центрировать")
        self.center_btn.setObjectName("center_btn")

        # Кнопка настройки приложения
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setContentsMargins(0, 0, -1, 0)
        self.gridLayout_9.setHorizontalSpacing(6)
        self.gridLayout_9.setVerticalSpacing(1)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.head_settings = QtWidgets.QPushButton(parent=self.centralwidget)
        self.head_settings.setEnabled(True)
        self.head_settings.setMinimumSize(QtCore.QSize(0, 70))
        self.head_settings.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/settings.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.head_settings.setIcon(icon5)
        self.head_settings.setIconSize(QtCore.QSize(45, 45))
        self.head_settings.setObjectName("pushButton_9")
        self.gridLayout_9.addWidget(self.head_settings, 18, 0, 1, 1)

        # Кнопка модуля нейросетей
        self.neuro_mode_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.neuro_mode_btn.setMinimumSize(QtCore.QSize(0, 70))
        self.neuro_mode_btn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/tab2.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon6.addPixmap(QtGui.QPixmap("icons/tab2.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.neuro_mode_btn.setIcon(icon6)
        self.neuro_mode_btn.setIconSize(QtCore.QSize(56, 56))
        self.neuro_mode_btn.setAutoDefault(False)
        self.neuro_mode_btn.setDefault(False)
        self.neuro_mode_btn.setObjectName("neuro_mode_btn")
        self.gridLayout_9.addWidget(self.neuro_mode_btn, 2, 0, 1, 1)

        # Кнопка модуля камер
        self.camera_mode_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.camera_mode_btn.setMinimumSize(QtCore.QSize(0, 70))
        self.camera_mode_btn.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/tab1.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.camera_mode_btn.setIcon(icon7)
        self.camera_mode_btn.setIconSize(QtCore.QSize(56, 56))
        self.camera_mode_btn.setObjectName("Camera_mode_btn")
        self.gridLayout_9.addWidget(self.camera_mode_btn, 1, 0, 1, 1)

        # кнопку модуля 3Д
        self.threeD_mode_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.threeD_mode_btn.sizePolicy().hasHeightForWidth())
        self.threeD_mode_btn.setSizePolicy(sizePolicy)
        self.threeD_mode_btn.setMinimumSize(QtCore.QSize(80, 70))
        self.threeD_mode_btn.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icons/tab3.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.threeD_mode_btn.setIcon(icon8)
        self.threeD_mode_btn.setIconSize(QtCore.QSize(66, 66))
        self.threeD_mode_btn.setObjectName("threeD_mode_btn")
        self.gridLayout_9.addWidget(self.threeD_mode_btn, 3, 0, 1, 1)

        # Иконка с желтым кристаллом
        icon0 = QtGui.QIcon()
        icon0.addPixmap(QtGui.QPixmap("icons/crystall.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.head_label = QtWidgets.QPushButton(parent=self.centralwidget)
        self.head_label.setMinimumSize(QtCore.QSize(80, 70))
        self.head_label.setMaximumSize(QtCore.QSize(1000, 70))
        self.head_label.setStyleSheet("border: 0px solid rgb(232, 174, 3);"
                                      "background-color: rgb(232, 174, 3)")
        self.head_label.setText("")
        self.head_label.setIcon(icon0)
        self.head_label.setObjectName("head_label")

        self.gridLayout_9.addWidget(self.head_label, 0, 0, 1, 1)
        self.gridLayout_9.setRowStretch(0, 1)
        self.gridLayout_9.setRowStretch(1, 1)
        self.gridLayout_9.setRowStretch(2, 1)
        self.gridLayout_9.setRowStretch(16, 1)
        self.gridLayout_10.addLayout(self.gridLayout_9, 0, 0, 1, 1)

        # Добавление в меню бар
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 963, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(parent=self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(parent=self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(parent=self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(parent=self.menubar)
        self.menu_4.setObjectName("menu_4")
        MainWindow.setMenuBar(self.menubar)
        self.action = QtGui.QAction(parent=MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtGui.QAction(parent=MainWindow)
        self.action_2.setObjectName("action_2")
        self.menu.addAction(self.action)
        self.menu.addAction(self.action_2)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())

        self.tabWidget.setTabVisible(0, False)
        self.tabWidget.setTabVisible(1, False)
        self.tabWidget.setTabVisible(2, False)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.videocam_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; text-decoration: underline; color:#ffffff;\">Видеокамеры</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_camera_mode), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_neuro_mode), _translate("MainWindow", "Tab 2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3d_mode), _translate("MainWindow", "Page"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.menu_2.setTitle(_translate("MainWindow", "Правка"))
        self.menu_3.setTitle(_translate("MainWindow", "Вид"))
        self.menu_4.setTitle(_translate("MainWindow", "Справка"))
        self.action.setText(_translate("MainWindow", "Открыть"))
        self.action_2.setText(_translate("MainWindow", "Сохранить"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec())
